version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-seguridad
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"     # Mapeo del puerto 3306 del contenedor al 3307 del host
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - seguridad_net

  app:
    image: deteccion-personas:latest
    container_name: app-detector
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./Personas_Detectadas:/app/Personas_Detectadas
    env_file: .env
    environment:
      RUTA_VIDEO: "rtsp://admin:2Mini001.@192.168.0.195"
      DB_HOST: db        # Aquí usás el nombre del servicio (db), no mysql-seguridad
      DB_PORT: "3306"    # Puerto interno del contenedor, no el mapeado (3307)
    networks:
      - seguridad_net

volumes:
  db_data:

networks:
  seguridad_net:
    driver: bridge
